version: "3.2"
services:
  apache:
    build:
      context: './apache/'
      dockerfile: development.dockerfile
      args:
       APACHE_VERSION: ${APACHE_VERSION}
       PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    networks:
      - backend
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}:/var/www/html
      - ./conf:/etc/apache2/pete-sites
    container_name: apache
  mysql:
    build:
      context: './mysql'
    command: --init-file /data/application/init.sql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_VERSION: "${MYSQL_VERSION}"
    volumes:
            - ./data:/var/lib/mysql
            - ./init.sql:/data/application/init.sql
    container_name: mysql
  dns:
    restart: always
    image: strm/dnsmasq
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    networks:
      - backend
    container_name: dnsmasq
networks:
  backend:
volumes:
    data:
