version: "3.2"
services:
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
       PHP_VERSION: ${PHP_VERSION}
       ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    networks:
      - backend
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}:/var/www/html
      - ./conf:/etc/apache2/pete-sites
    container_name: apache
  mysql:
    build:
      context: './mysql'
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_VERSION: "${MYSQL_VERSION}"
    volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/init.sql:/data/application/init.sql
            - ./mysql/windows_my.cnf:/etc/my.cnf
    container_name: mysql
networks:
  backend:
volumes:
    data:
